### ISSUE TITLE
Component instance NOT getting created.

### ISSUE THREAD

**Issue by gauripadbidri** [node-xmpp/node-xmpp-component#27]
HI All,

I am new to using Node and XMPP. This is probably a very simple issue for you all, but I am unable to create the "Component" instance. Following is my Code : 

<code>var Component = require('node-xmpp-component');</code>
<code>var component = new Component({jid: 'adminuser@host.com', password: 'adminpassword', host: 'XMPP IP Address', port: 5222});</code>
When I instantiate the Component object, NONE of my events get triggered for obvious reasons that the object does not get created.

Following are my questions : 
1. We access our XMPP <b>Ejabberd </b>Server via IP Address. Also, <b>my Ejabberd Server is </b>REMOTE and <b>NOT on my Local Machine</b>
2. The JID, Password provided to the Component Constructor have admin privilages.
3. I am using Ejabberd latest version, is that an issue ?
4. What modules should be registered to get it working ? I have In Band registration already enabled.

Where am I going wrong ? Please help !

**Comment by sonnyp** [comment]
You're trying to use XMPP component as a client, use https://github.com/node-xmpp/node-xmpp-client if you need a client otherwise changes your component settings.
