### ISSUE TITLE
get archive messages and vcards

### ISSUE THREAD

**Issue by liorru** [node-xmpp/node-xmpp-component#28]
Hi,
I building an external component  which need to fetch all message archive for given jid
is it possible? 

also is it possible to get a vcard for a given jid?

thanks

**Comment by lloydwatkin** [comment]
I'd suggest you ask those questions via the JDev mailing list (http://mail.jabber.org/mailman/listinfo/jdev) or via the jdev chat room (xmpp:jdev@conference.jabber.org) :)
